// This file will be generated by FlutterFire CLI
// You'll need to run: flutterfire configure 

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return const FirebaseOptions(
      apiKey: 'AIzaSyBhQFsQgJ8Hy1YsJog_qHieYn572Ba9k8s',
      appId: '1:766555871151:android:a32ff8d8898d545291c15a',
      messagingSenderId: '766555871151',
      projectId: 'diskorff-e6f0e',
      storageBucket: 'diskorff-e6f0e.appspot.com',
    );
  }
} 